# -*- coding: utf-8 -*-
"""CS110A Assignment 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6znQhqqrJISgGOehu2xXf_eUMRiXizj
"""

#Nancy Chen
#Programming Assignment 6: Parallelogram Program
#CS 110A Assignment 6
#This program creates accumulator pattern parallelogram 

"""function to draw the parallelogram by repeating characters"""
def repeatChar(numRepeats, outputChar):
    '''
    output the outputChar numRepeats times on the same line
    '''
    for colNo in range(numRepeats):
        print(outputChar, end='')  # print outputChar and stay on the same line (don't go to next line)

"""main portion of program
   first for loop creates the characters increasing for first triangle
   second for loop has characters decreasing for second triangle 
"""
def main():
  print("This program will output a parallelogram.")
  number = int(input("How long do you want each side to be? "))
  character = input("Please enter the character you want it to be made of: ")

  for i in range(number):
    repeatChar(i, character)
    print('')

  for i in range(number, 0, -1):
    repeatChar(number - i, ' ') #the space that goes before the character
    repeatChar(i, character) 
    print('')
    
main()

"""
Sample output 1: 
This program will output a parallelogram.
How long do you want each side to be? 5
Please enter the character you want it to be made of: *

*
**
***
****
*****
 ****
  ***
   **
    *

"""
"""
Sample output 2:

This program will output a parallelogram.
How long do you want each side to be? 15
Please enter the character you want it to be made of: )

)
))
)))
))))
)))))
))))))
)))))))
))))))))
)))))))))
))))))))))
)))))))))))
))))))))))))
)))))))))))))
))))))))))))))
)))))))))))))))
 ))))))))))))))
  )))))))))))))
   ))))))))))))
    )))))))))))
     ))))))))))
      )))))))))
       ))))))))
        )))))))
         ))))))
          )))))
           ))))
            )))
             ))
              )

"""