# -*- coding: utf-8 -*-
"""CS110A assignment 9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pddwGygWjUD1sHI48Sb5LjWCRjwyWWk2
"""

#Nancy Chen
#Programming Assignment 9: Palindrome Program
#CS 110A Assignment 9
# This program creates a palindrome program 

"""
the user inputs a word and tests if it is a palindrome 
checks if palindrome, return true 
if not palindrome, returns false 
"""

def checkPalindromeWord(word):

  #stops if word does not have the same letters 
    for letters in range(0, len(word)): #for the range of length of variable word
        word = word.lower()
        if word[letters] != word[-letters -1]:
            return False   
    else:
        return True 

def main():

    word = input("Please enter a word ")

    while word: 
      if checkPalindromeWord(word): 
        print("The word you entered: '" + str(word) + "' is a palindrome")
      else: 
        print("The word you entered: '" + str(word) + "' is not a palindrome")
      askagain = input("Do you want to enter another word? ").lower()
      if askagain == "y" or askagain == "yes":
          word = input("Please enter a word ")
      elif askagain == "n" or askagain == "no": 
          break

main()

"""
Sample output: 

Please enter a word TACO
The word you entered: 'TACO' is not a palindrome
Do you want to enter another word? YES
Please enter a word chocolate
The word you entered: 'chocolate' is not a palindrome
Do you want to enter another word? Y
Please enter a word abcdefedcba
The word you entered: 'abcdefedcba' is a palindrome
Do you want to enter another word? yes
Please enter a word radar
The word you entered: 'radar' is a palindrome
Do you want to enter another word? no

Please enter a word abcCBA
The word you entered: 'abcCBA' is a palindrome
Do you want to enter another word? Y
Please enter a word potato
The word you entered: 'potato' is not a palindrome
Do you want to enter another word? YeS
Please enter a word abcdecba
The word you entered: 'abcdecba' is not a palindrome
Do you want to enter another word? n

"""

#Nancy Chen
#Programming Assignment 9: Palindrome Program Extra Credit
#CS 110A Assignment 9
#for extra credit - checking if a phrase is a palindrome

"""
function removes punctuation and spacing from user input
"""
def removePunctuation(phrase):

  phrase = phrase.lower()
  punctuation = '''" "'.!,();'''
  newphrase = ""

  for eachLetter in phrase: 
    if eachLetter not in punctuation:
        newphrase = newphrase + eachLetter
  return newphrase

"""
function deduces if phrase is a palindrome 
if not a palindrome will return false 
if a palindrome will return true 
"""
def checkPalindromePhrase(newphrase):
    
    for eachLetter in range(0, len(newphrase)):  #for the range of length of variable word
        newphrase = newphrase.lower()
        if newphrase[eachLetter] != newphrase[-eachLetter -1]: 
            return False 
    else:
        return True

def main():

  phrase = input("Please enter a word or phrase: ")

  while phrase:  
    newphrase = removePunctuation(phrase)
    checkPalindromePhrase(newphrase)

    if checkPalindromePhrase(newphrase): 
      print("The text you entered: '" + str(phrase) + "' is a palindrome")
    else: 
      print("The text you entered: '" + str(phrase) + "' is not a palindrome")
    askagain = input("Do you want to enter another? ").lower() 
    if askagain == "y" or askagain == "yes":
        phrase = input("Please enter a word or phrase: ") 
    elif askagain == "n" or askagain == "no": 
          break

main()

"""
Sample output:

Please enter a word or phrase: Madam In Eden, I'm Adam
The text you entered: 'Madam In Eden, I'm Adam' is a palindrome
Do you want to enter another? YeS
Please enter a word or phrase: TacoBell
The text you entered: 'TacoBell' is not a palindrome
Do you want to enter another? Yes
Please enter a word or phrase: No sir, away! A papaya war is on!
The text you entered: 'No sir, away! A papaya war is on!' is a palindrome
Do you want to enter another? N

Please enter a word or phrase: NEVER!! ODD!! OR!! EVEN!!
The text you entered: 'NEVER!! ODD!! OR!! EVEN!!' is a palindrome
Do you want to enter another? y
Please enter a word or phrase: Taco Cat!!!!
The text you entered: 'Taco Cat!!!!' is a palindrome
Do you want to enter another? yes
Please enter a word or phrase: Madam, I'm Adam !
The text you entered: 'Madam, I'm Adam !' is a palindrome
Do you want to enter another? no

"""