# -*- coding: utf-8 -*-
"""CS110A assignment 10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uu-DlVTxY0JUSb0wD1rnGuS825OZZYVz
"""

#Nancy Chen
#Programming Assignment 10: De-Dup Program
#CS 110A Assignment 10
#This program removes duplicates from user input 

"""
removes duplicates from user input
"""
def removeDuplicate(listNum):

  noDupes = []
  for number in listNum:
    if number not in noDupes:
      noDupes.append(number)
  return noDupes

"""
checks how many unique numbers are in the list
"""
def uniqueNum(noDupes):

  count = 0 #counting how many numbers there are that are unique in a list
  for numbers in range(len(noDupes)): 
      count += 1

  print("You entered " + str(count) + " unique numbers:")
  for numbers in range(len(noDupes)): #puts the list of numbers in a single line, spaced out
    print(noDupes[numbers], end = " ")
  return noDupes

"""
outputs minimum and maximum number
"""
def maxAndMin(noDupes):

  minValue = noDupes[0]
  for numbers in range(len(noDupes)):
    if noDupes[numbers] < minValue:
      minValue = noDupes[numbers]

  maxValue = noDupes[0]
  for numbers in range(len(noDupes)):
    if noDupes[numbers] > maxValue:
      maxValue = noDupes[numbers]

  print(f"\nwith one minimum value: {minValue} and one maximum value: {maxValue}")

def main(): 

  listNum = []

  posInt = print("Please enter some positive integers, hitting return after each one. Enter 'q' to quit: ")
  while posInt != "q": 
    posInt = input()
    if posInt.isnumeric():
      posInt = int(posInt)
      listNum.append(posInt)
    else:
      break

  noDupes = removeDuplicate(listNum) 
  noDupes = uniqueNum(noDupes) 
  if len(noDupes) != 0:
    maxAndMin(noDupes)

main() 

"""
Sample output:
Please enter some positive integers, hitting return after each one. Enter 'q' to quit: 
5
4
-3
You entered 2 unique numbers:
5 4 
with one minimum value: 4 and one maximum value: 5


Please enter some positive integers, hitting return after each one. Enter 'q' to quit: 
10
5
9
1
5
10
1
q
You entered 4 unique numbers:
10 5 9 1 
with one minimum value: 1 and one maximum value: 10


Please enter some positive integers, hitting return after each one. Enter 'q' to quit: 
5.6
You entered 0 unique numbers:

Please enter some positive integers, hitting return after each one. Enter 'q' to quit: 
55
22
205
22
75
42
68
q
You entered 6 unique numbers:
55 22 205 75 42 68 
with one minimum value: 22 and one maximum value: 205

"""

def main(): 

  listNum = []

  posInt = print("Please enter some positive integers, hitting return after each one. Enter 'q' to quit: ")
  while posInt != "q": 
    posInt = input()
    if posInt.isnumeric():
      posInt = int(posInt)
      listNum.append(posInt)
    else: 
      break

  noDupes = removeDuplicate(listNum) 
  noDupes = uniqueNum(noDupes) 
  maxAndMin(noDupes) #elif/else statement still runs this

main()