# -*- coding: utf-8 -*-
"""CS110A Assignment 14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QZaqxRhzlejeM628J7PwF_A-XfjAreRh
"""

#CS110A Assignment 14 - Extra Credit
#Nancy Chen
#Random number guessing game

import random

def main():

  ask = "y"
  while ask.lower():
    times = int(input("How many times do you want to guess a number between 1 and 10? "))
    randomizednums = randomnumber(times)
    print(f"{times} random numbers between 1 and 10 have been generated")

    guessnumber(randomizednums)

    print("These are the random numbers that were picked: ")
    for num in randomizednums:
      print(num, end = " ")
    print("")

    evenorodd(randomizednums)
    
    ask = input("Do you want to play again? ")
    if ask[0] != "y" or ask[0] != "Y":
      break

"""
generates random numbers for user to guess
"""
def randomnumber(times):
  
  randomizednums = []
  for number in range(times):
    num = random.randint(1,10)
    randomizednums.append(num)
  return randomizednums

"""
allows user to guess the numbers that were randomized
"""
def guessnumber(randomizednums):

  guesses = []

  for nums in range(len(randomizednums)):
    guess = int(input("Please guess a number: "))
    if guess == int(randomizednums[nums]):
      print("You're a genius! You're correct!")
    elif guess != int(randomizednums[nums]):
      print("You're wrong! But you are still smart!")

"""
separates even and odd randomized numbers
""" 
def evenorodd(randomizednums):

  even_nums = []
  odd_nums = []
  for num in randomizednums:
    if num % 2 == 0:
      even_nums.append(num)
    else:
      odd_nums.append(num)

  print("The following numbers are even: ")
  for num in even_nums:
      print(num, end = " ")
  print("")

  print("The following numbers are odd: ")
  for num in odd_nums:
      print(num, end = " ")
  print("")

main()

"""
Sample output:

How many times do you want to guess a number between 1 and 10? 2
2 random numbers between 1 and 10 have been generated
Please guess a number: 10
You're a genius! You're correct!
Please guess a number: 9
You're wrong! But you are still smart!
These are the random numbers that were picked: 
10 6 
The following numbers are even: 
10 6 
The following numbers are odd: 

Do you want to play again? YES
How many times do you want to guess a number between 1 and 10? 3
3 random numbers between 1 and 10 have been generated
Please guess a number: 8
You're wrong! But you are still smart!
Please guess a number: 7
You're a genius! You're correct!
Please guess a number: 1
You're wrong! But you are still smart!
These are the random numbers that were picked: 
4 7 9 
The following numbers are even: 
4 
The following numbers are odd: 
7 9 
Do you want to play again? no

How many times do you want to guess a number between 1 and 10? 3
3 random numbers between 1 and 10 have been generated
Please guess a number: 9
You're wrong! But you are still smart!
Please guess a number: 8
You're wrong! But you are still smart!
Please guess a number: 3
You're a genius! You're correct!
These are the random numbers that were picked: 
4 9 3 
The following numbers are even: 
4 
The following numbers are odd: 
9 3 
Do you want to play again? no
"""