# -*- coding: utf-8 -*-
"""CS110 Assignment 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkNjz_Xt8MQ8pa17Q5DanQNNoCVApDPl
"""

#Nancy Chen
#Programming Assignment 7: Rock-Paper-Scissors Program
#CS 110A Assignment 7
#This program creates a rock-paper-scissors program

import random 

"""
function for user to input move
"""

def checkMove(): 

  user_move = input("Please enter your move: Paper, Rock, or Scissors: ").lower()
  return user_move 

"""
function for randomized computer move
"""

def compMove(): 

  #computer will randomly select rock paper scissors
  rock = 1
  paper = 2
  scissors = 3
  comp_num = int(random.randrange(1,4))

  if comp_num == 1:
    comp_move = "rock"
    print("Computer's move is " + str(comp_move)) 
    
  if comp_num == 2: 
    comp_move = "paper"
    print("Computer's move is " + str(comp_move)) 

  if comp_num == 3: 
    comp_move = "scissors"
    print("Computer's move is " + str(comp_move)) 

  return comp_move

"""
function that shows rock paper scissors move input by user will output different outcomes
will also show computer output based on user's move
checks if user move is valid
"""

def rockPaperScissors(user_move, comp_move):

  #check user_move for invalid input values

  if user_move.lower() != 'scissors' and user_move.lower() != 'scissor' and user_move.lower() != 'rock' and user_move.lower() != 'rocks' and user_move.lower() != 'paper' and user_move.lower() != 'papers':
      print("Invalid move!!")

  #if user move is paper, all outcomes possible for paper

  if (user_move.lower() == 'paper' or user_move.lower() == 'papers') and comp_move == 'scissors':
    print("Computer wins! Scissors cuts paper!")
  elif (user_move.lower() == 'paper' or user_move.lower() == 'papers') and comp_move == 'rock':
    print("You win! Paper covers rock!")
  elif (user_move.lower() == 'paper' or user_move.lower() == 'papers') and comp_move == 'paper':
    print("Tie with " + str(comp_move))

  #if user move is rock, all outcomes possible for rock

  if (user_move.lower() == 'rock' or user_move.lower() == 'rocks') and comp_move == 'paper': 
    print("Computer wins! Paper covers rock!")
  elif (user_move.lower() == 'rock' or user_move.lower() == 'rocks') and comp_move == 'scissors':
    print("You win! Rock beats scissors!")
  elif (user_move.lower() == 'rock' or user_move.lower() == 'rocks') and comp_move == 'rock':
    print("Tie with " + str(comp_move))

  #if user move is scissors, all outcomes possible for scissors

  if (user_move.lower() == 'scissors' or user_move.lower() == 'scissor') and comp_move == 'rock':
    print("Computer wins! Rock beats scissors!")
  elif (user_move.lower() == 'scissors' or user_move.lower() == 'scissor') and comp_move == 'paper':
    print("You win! Scissors cuts paper!")
  elif (user_move.lower() == 'scissors' or user_move.lower() == 'scissor') and comp_move == 'scissors':
     print("Tie with " + str(comp_move))

def main():
  userMove = checkMove()
  computerMove = compMove()
  rockPaperScissors(userMove, computerMove)

main()

"""
Sample output: 
Please enter your move: Paper, Rock, or Scissors: SCISSOR
Computer's move is scissors
Tie with scissors
"""

"""
Sample output: 
Please enter your move: Paper, Rock, or Scissors: ROCKS
Computer's move is paper
Computer wins! Paper covers rock!
"""

"""
Sample output:
Please enter your move: Paper, Rock, or Scissors: rivers
Computer's move is scissors
Invalid move!!
"""