# -*- coding: utf-8 -*-
"""CS110A assignment 11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1acfN8YEVLSCoZPOfD67jhTOZV6ji-wTi
"""

#Nancy Chen
#Programming Assignment 11: Courses and Test Scores
#CS 110A Assignment 11
#This program stores all test scores for a student 

def main():

  classAmnt = int(input("How many courses are you taking? "))
  averageScores = classes(classAmnt)
  highestAverage(averageScores)
    
"""
for-loop to cycle through classes and class test scores in a nested list
"""
def classes(classAmnt):

  allTests = []

  #for loop to get userinput about what scores are for each class
  for classes in range(1, classAmnt + 1):
    testAmnt = int(input(f"How many tests are in course number {classes}? "))
    classTestScores = []
    for tests in range(1, testAmnt + 1):
      testScore = int(input(f"What was your score for test {tests} for course {classes}? "))
      classTestScores.append(testScore)
    allTests.append(classTestScores)

  #calculates average scores of each nested list
  averageScores = []
  count = 0
  for course in allTests:
    total = 0
    count += 1
    for test in course:
      total = total + test
    average = total/len(course)
    averageScores.append(average)
    print(f"The average for course {count} is {average:.2f}")
  return averageScores

"""
calculates highest average out of all averages
"""
def highestAverage(averageScores):

  highestAvg = 0
  for score in averageScores: 
    if score >= highestAvg:
      highestAvg = score
  print(f"The highest average score is {highestAvg:.2f}")

main()

"""
Sample output:
How many courses are you taking? 2
How many tests are in course number 1? 3
What was your score for test 1 for course 1? 70
What was your score for test 2 for course 1? 80
What was your score for test 3 for course 1? 90
How many tests are in course number 2? 4
What was your score for test 1 for course 2? 75
What was your score for test 2 for course 2? 80
What was your score for test 3 for course 2? 85
What was your score for test 4 for course 2? 90
The average for course 1 is 80.00
The average for course 2 is 82.50
The highest average score is 82.50

How many courses are you taking? 4
How many tests are in course number 1? 3
What was your score for test 1 for course 1? 100
What was your score for test 2 for course 1? 80
What was your score for test 3 for course 1? 90
How many tests are in course number 2? 5
What was your score for test 1 for course 2? 10
What was your score for test 2 for course 2? 40
What was your score for test 3 for course 2? 78
What was your score for test 4 for course 2? 35
What was your score for test 5 for course 2? 86
How many tests are in course number 3? 2
What was your score for test 1 for course 3? 67
What was your score for test 2 for course 3? 30
How many tests are in course number 4? 3
What was your score for test 1 for course 4? 100
What was your score for test 2 for course 4? 98
What was your score for test 3 for course 4? 87
The average for course 1 is 90.00
The average for course 2 is 49.80
The average for course 3 is 48.50
The average for course 4 is 95.00
The highest average score is 95.00

How many courses are you taking? 2
How many tests are in course number 1? 2
What was your score for test 1 for course 1? 100
What was your score for test 2 for course 1? 60
How many tests are in course number 2? 3
What was your score for test 1 for course 2? 76
What was your score for test 2 for course 2? 80
What was your score for test 3 for course 2? 54
The average for course 1 is 80.00
The average for course 2 is 70.00
The highest average score is 80.00
"""