# -*- coding: utf-8 -*-
"""CS 110A Assignment 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlQ2QW6mCd7eypsoRHahNWboECvRYUim
"""

#Nancy Chen
#Programming Assignment 5: Rolling Dice
#CS 110A Assignment 5
#This program creates random dice rolls 

import random 

#Write at least one function to simulate the rolling of dice and call that function in a loop for each player

def diceRolls(tempPlayer, tempNum, tempSides):
  total = 0
  for i in range(1, tempNum + 1):
    dice_throws = random.randrange(1, tempSides + 1)
    print("Player", str(tempPlayer), "rolled: " + str(dice_throws))
    total += dice_throws
  return  print("That totals:", total)

#main part of program
numPlayers = int(input("How many players are rolling dice? "))
diceNum = int(input("How many dice does each player roll? "))
diceSides = int(input("How many sides does each die have? "))

for i in range(1, numPlayers + 1):
  diceRolls(i, diceNum, diceSides)

"""
Sample output: 

How many players are rolling dice? 2
How many dice does each player roll? 3
How many sides does each die have? 6
Player 1 rolled: 4
Player 1 rolled: 1
Player 1 rolled: 5
That totals: 10

Player 2 rolled: 2
Player 2 rolled: 3
Player 2 rolled: 5
That totals: 10

"""

"""
Sample output: 

How many players are rolling dice? 5
How many dice does each player roll? 2
How many sides does each die have? 10
Player 1 rolled: 2
Player 1 rolled: 1
That totals: 3
Player 2 rolled: 6
Player 2 rolled: 2
That totals: 8
Player 3 rolled: 2
Player 3 rolled: 4
That totals: 6
Player 4 rolled: 8
Player 4 rolled: 7
That totals: 15
Player 5 rolled: 6
Player 5 rolled: 7
That totals: 13

"""